version: "3"

services:
  app:
    image: tic-tac-toe:latest
    build:
      dockerfile: docker/development/Dockerfile
      context: .
    env_file: docker/development/Envfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - .:/app
    entrypoint: docker/entrypoint.sh
    command: bundle exec puma -C config/puma.rb

  postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test:
    image: tic-tac-toe:latest
    # env_file: ./docker/test/Envfile
    depends_on:
      - postgres
    volumes:
      - .:/app

  ui:
    image: node:15.5.1-alpine3.12
    ports:
      - 3011:3000
    working_dir: /home
    volumes:
      - ./ui:/home
      - node_modules:/home/node_modules
    command: yarn run start

volumes:
  # redis:
  postgres_data:
  node_modules:
  sqlite3_db:
