default: &default
  adapter: postgresql
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  
development:
  <<: *default
  database: tictactoe_development

production:
  <<: *default
  database: tictactoe_production

test:
  <<: *default
  database: tictactoe_test
